// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rangedb.proto

package rangedbpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EventsRequest struct {
	StartingWithEventNumber uint64   `protobuf:"varint,1,opt,name=startingWithEventNumber,proto3" json:"startingWithEventNumber,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *EventsRequest) Reset()         { *m = EventsRequest{} }
func (m *EventsRequest) String() string { return proto.CompactTextString(m) }
func (*EventsRequest) ProtoMessage()    {}
func (*EventsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_40660d2deccf2909, []int{0}
}

func (m *EventsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventsRequest.Unmarshal(m, b)
}
func (m *EventsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventsRequest.Marshal(b, m, deterministic)
}
func (m *EventsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventsRequest.Merge(m, src)
}
func (m *EventsRequest) XXX_Size() int {
	return xxx_messageInfo_EventsRequest.Size(m)
}
func (m *EventsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EventsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EventsRequest proto.InternalMessageInfo

func (m *EventsRequest) GetStartingWithEventNumber() uint64 {
	if m != nil {
		return m.StartingWithEventNumber
	}
	return 0
}

type EventsByStreamRequest struct {
	StreamName              string   `protobuf:"bytes,1,opt,name=streamName,proto3" json:"streamName,omitempty"`
	StartingWithEventNumber uint64   `protobuf:"varint,2,opt,name=startingWithEventNumber,proto3" json:"startingWithEventNumber,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *EventsByStreamRequest) Reset()         { *m = EventsByStreamRequest{} }
func (m *EventsByStreamRequest) String() string { return proto.CompactTextString(m) }
func (*EventsByStreamRequest) ProtoMessage()    {}
func (*EventsByStreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_40660d2deccf2909, []int{1}
}

func (m *EventsByStreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventsByStreamRequest.Unmarshal(m, b)
}
func (m *EventsByStreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventsByStreamRequest.Marshal(b, m, deterministic)
}
func (m *EventsByStreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventsByStreamRequest.Merge(m, src)
}
func (m *EventsByStreamRequest) XXX_Size() int {
	return xxx_messageInfo_EventsByStreamRequest.Size(m)
}
func (m *EventsByStreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EventsByStreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EventsByStreamRequest proto.InternalMessageInfo

func (m *EventsByStreamRequest) GetStreamName() string {
	if m != nil {
		return m.StreamName
	}
	return ""
}

func (m *EventsByStreamRequest) GetStartingWithEventNumber() uint64 {
	if m != nil {
		return m.StartingWithEventNumber
	}
	return 0
}

type EventsByAggregateTypeRequest struct {
	AggregateTypes          []string `protobuf:"bytes,1,rep,name=aggregateTypes,proto3" json:"aggregateTypes,omitempty"`
	StartingWithEventNumber uint64   `protobuf:"varint,2,opt,name=startingWithEventNumber,proto3" json:"startingWithEventNumber,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *EventsByAggregateTypeRequest) Reset()         { *m = EventsByAggregateTypeRequest{} }
func (m *EventsByAggregateTypeRequest) String() string { return proto.CompactTextString(m) }
func (*EventsByAggregateTypeRequest) ProtoMessage()    {}
func (*EventsByAggregateTypeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_40660d2deccf2909, []int{2}
}

func (m *EventsByAggregateTypeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventsByAggregateTypeRequest.Unmarshal(m, b)
}
func (m *EventsByAggregateTypeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventsByAggregateTypeRequest.Marshal(b, m, deterministic)
}
func (m *EventsByAggregateTypeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventsByAggregateTypeRequest.Merge(m, src)
}
func (m *EventsByAggregateTypeRequest) XXX_Size() int {
	return xxx_messageInfo_EventsByAggregateTypeRequest.Size(m)
}
func (m *EventsByAggregateTypeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EventsByAggregateTypeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EventsByAggregateTypeRequest proto.InternalMessageInfo

func (m *EventsByAggregateTypeRequest) GetAggregateTypes() []string {
	if m != nil {
		return m.AggregateTypes
	}
	return nil
}

func (m *EventsByAggregateTypeRequest) GetStartingWithEventNumber() uint64 {
	if m != nil {
		return m.StartingWithEventNumber
	}
	return 0
}

type Record struct {
	AggregateType        string   `protobuf:"bytes,1,opt,name=AggregateType,proto3" json:"AggregateType,omitempty"`
	AggregateID          string   `protobuf:"bytes,2,opt,name=AggregateID,proto3" json:"AggregateID,omitempty"`
	GlobalSequenceNumber uint64   `protobuf:"varint,3,opt,name=GlobalSequenceNumber,proto3" json:"GlobalSequenceNumber,omitempty"`
	StreamSequenceNumber uint64   `protobuf:"varint,4,opt,name=StreamSequenceNumber,proto3" json:"StreamSequenceNumber,omitempty"`
	InsertTimestamp      uint64   `protobuf:"varint,5,opt,name=InsertTimestamp,proto3" json:"InsertTimestamp,omitempty"`
	EventID              string   `protobuf:"bytes,6,opt,name=EventID,proto3" json:"EventID,omitempty"`
	EventType            string   `protobuf:"bytes,7,opt,name=EventType,proto3" json:"EventType,omitempty"`
	Data                 string   `protobuf:"bytes,8,opt,name=Data,proto3" json:"Data,omitempty"`
	Metadata             string   `protobuf:"bytes,9,opt,name=Metadata,proto3" json:"Metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_40660d2deccf2909, []int{3}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetAggregateType() string {
	if m != nil {
		return m.AggregateType
	}
	return ""
}

func (m *Record) GetAggregateID() string {
	if m != nil {
		return m.AggregateID
	}
	return ""
}

func (m *Record) GetGlobalSequenceNumber() uint64 {
	if m != nil {
		return m.GlobalSequenceNumber
	}
	return 0
}

func (m *Record) GetStreamSequenceNumber() uint64 {
	if m != nil {
		return m.StreamSequenceNumber
	}
	return 0
}

func (m *Record) GetInsertTimestamp() uint64 {
	if m != nil {
		return m.InsertTimestamp
	}
	return 0
}

func (m *Record) GetEventID() string {
	if m != nil {
		return m.EventID
	}
	return ""
}

func (m *Record) GetEventType() string {
	if m != nil {
		return m.EventType
	}
	return ""
}

func (m *Record) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *Record) GetMetadata() string {
	if m != nil {
		return m.Metadata
	}
	return ""
}

func init() {
	proto.RegisterType((*EventsRequest)(nil), "rangedbpb.EventsRequest")
	proto.RegisterType((*EventsByStreamRequest)(nil), "rangedbpb.EventsByStreamRequest")
	proto.RegisterType((*EventsByAggregateTypeRequest)(nil), "rangedbpb.EventsByAggregateTypeRequest")
	proto.RegisterType((*Record)(nil), "rangedbpb.Record")
}

func init() { proto.RegisterFile("rangedb.proto", fileDescriptor_40660d2deccf2909) }

var fileDescriptor_40660d2deccf2909 = []byte{
	// 392 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0xcf, 0x4e, 0xc2, 0x40,
	0x10, 0xc6, 0x2d, 0x60, 0xa1, 0x63, 0xc0, 0xb0, 0xd1, 0xd8, 0x10, 0x62, 0x1a, 0x62, 0x94, 0x13,
	0x31, 0x78, 0xd1, 0xa3, 0xa4, 0xc6, 0xf4, 0x20, 0x87, 0x42, 0xc2, 0x79, 0x0b, 0x93, 0xda, 0x84,
	0xfe, 0x61, 0x77, 0x31, 0xe1, 0xe6, 0x13, 0xf9, 0x20, 0x3e, 0x95, 0xe9, 0x96, 0x42, 0x5b, 0x0b,
	0x07, 0xbd, 0xed, 0xfe, 0x3e, 0xf6, 0x9b, 0x19, 0xe6, 0x2b, 0x34, 0x19, 0x0d, 0x5c, 0x5c, 0x38,
	0x83, 0x88, 0x85, 0x22, 0x24, 0xda, 0xf6, 0x1a, 0x39, 0x3d, 0x0b, 0x9a, 0x2f, 0x1f, 0x18, 0x08,
	0x6e, 0xe3, 0x6a, 0x8d, 0x5c, 0x90, 0x47, 0xb8, 0xe2, 0x82, 0x32, 0xe1, 0x05, 0xee, 0xcc, 0x13,
	0xef, 0x52, 0x1c, 0xaf, 0x7d, 0x07, 0x99, 0xae, 0x18, 0x4a, 0xbf, 0x66, 0x1f, 0x92, 0x7b, 0x2b,
	0xb8, 0x4c, 0xac, 0x46, 0x9b, 0x89, 0x60, 0x48, 0xfd, 0xd4, 0xf2, 0x1a, 0x80, 0x4b, 0x30, 0xa6,
	0x3e, 0x4a, 0x17, 0xcd, 0xce, 0x90, 0x63, 0x25, 0x2b, 0xc7, 0x4b, 0x7e, 0x2a, 0xd0, 0x4d, 0x6b,
	0x3e, 0xbb, 0x2e, 0x43, 0x97, 0x0a, 0x9c, 0x6e, 0x22, 0x4c, 0x4b, 0xdf, 0x42, 0x8b, 0x66, 0x39,
	0xd7, 0x15, 0xa3, 0xda, 0xd7, 0xec, 0x02, 0xfd, 0x47, 0x0b, 0xdf, 0x15, 0x50, 0x6d, 0x9c, 0x87,
	0x6c, 0x41, 0x6e, 0xa0, 0x99, 0x6b, 0x62, 0x3b, 0x6a, 0x1e, 0x12, 0x03, 0xce, 0x76, 0xc0, 0x32,
	0xa5, 0xbd, 0x66, 0x67, 0x11, 0x19, 0xc2, 0xc5, 0xeb, 0x32, 0x74, 0xe8, 0x72, 0x12, 0x4f, 0x11,
	0xcc, 0x71, 0xdb, 0x49, 0x55, 0x76, 0x52, 0xaa, 0xc5, 0x6f, 0x92, 0x3f, 0xbd, 0xf0, 0xa6, 0x96,
	0xbc, 0x29, 0xd3, 0x48, 0x1f, 0xce, 0xad, 0x80, 0x23, 0x13, 0x53, 0xcf, 0x47, 0x2e, 0xa8, 0x1f,
	0xe9, 0xa7, 0xf2, 0xe7, 0x45, 0x4c, 0x74, 0xa8, 0xcb, 0x99, 0x2d, 0x53, 0x57, 0x65, 0xbf, 0xe9,
	0x95, 0x74, 0x41, 0x93, 0x47, 0x39, 0x6f, 0x5d, 0x6a, 0x7b, 0x40, 0x08, 0xd4, 0x4c, 0x2a, 0xa8,
	0xde, 0x90, 0x82, 0x3c, 0x93, 0x0e, 0x34, 0xde, 0x50, 0xd0, 0x45, 0xcc, 0x35, 0xc9, 0x77, 0xf7,
	0xe1, 0x57, 0x05, 0xea, 0x76, 0x9c, 0x4d, 0x73, 0x44, 0x9e, 0x40, 0x4d, 0x56, 0x4b, 0xf4, 0xc1,
	0x2e, 0xaf, 0x83, 0x5c, 0x58, 0x3b, 0xed, 0x8c, 0x92, 0x2c, 0xa1, 0x77, 0x72, 0xaf, 0x10, 0x0b,
	0x5a, 0xf9, 0x24, 0x12, 0xe3, 0x97, 0x45, 0x21, 0xa4, 0x87, 0xac, 0x66, 0xfb, 0x50, 0xe7, 0xd7,
	0x78, 0x57, 0xe2, 0x58, 0x16, 0xc1, 0x43, 0xc6, 0x26, 0xb4, 0x27, 0x6b, 0x87, 0xcf, 0x99, 0xe7,
	0xe0, 0x34, 0xfc, 0xe3, 0xa4, 0x8e, 0x2a, 0x3f, 0xe8, 0x87, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x67, 0x6d, 0xf8, 0x7e, 0xe1, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RangeDBClient is the client API for RangeDB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RangeDBClient interface {
	Events(ctx context.Context, in *EventsRequest, opts ...grpc.CallOption) (RangeDB_EventsClient, error)
	EventsByStream(ctx context.Context, in *EventsByStreamRequest, opts ...grpc.CallOption) (RangeDB_EventsByStreamClient, error)
	EventsByAggregateType(ctx context.Context, in *EventsByAggregateTypeRequest, opts ...grpc.CallOption) (RangeDB_EventsByAggregateTypeClient, error)
	SubscribeToEvents(ctx context.Context, in *EventsRequest, opts ...grpc.CallOption) (RangeDB_SubscribeToEventsClient, error)
}

type rangeDBClient struct {
	cc grpc.ClientConnInterface
}

func NewRangeDBClient(cc grpc.ClientConnInterface) RangeDBClient {
	return &rangeDBClient{cc}
}

func (c *rangeDBClient) Events(ctx context.Context, in *EventsRequest, opts ...grpc.CallOption) (RangeDB_EventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RangeDB_serviceDesc.Streams[0], "/rangedbpb.RangeDB/Events", opts...)
	if err != nil {
		return nil, err
	}
	x := &rangeDBEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RangeDB_EventsClient interface {
	Recv() (*Record, error)
	grpc.ClientStream
}

type rangeDBEventsClient struct {
	grpc.ClientStream
}

func (x *rangeDBEventsClient) Recv() (*Record, error) {
	m := new(Record)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *rangeDBClient) EventsByStream(ctx context.Context, in *EventsByStreamRequest, opts ...grpc.CallOption) (RangeDB_EventsByStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RangeDB_serviceDesc.Streams[1], "/rangedbpb.RangeDB/EventsByStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &rangeDBEventsByStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RangeDB_EventsByStreamClient interface {
	Recv() (*Record, error)
	grpc.ClientStream
}

type rangeDBEventsByStreamClient struct {
	grpc.ClientStream
}

func (x *rangeDBEventsByStreamClient) Recv() (*Record, error) {
	m := new(Record)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *rangeDBClient) EventsByAggregateType(ctx context.Context, in *EventsByAggregateTypeRequest, opts ...grpc.CallOption) (RangeDB_EventsByAggregateTypeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RangeDB_serviceDesc.Streams[2], "/rangedbpb.RangeDB/EventsByAggregateType", opts...)
	if err != nil {
		return nil, err
	}
	x := &rangeDBEventsByAggregateTypeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RangeDB_EventsByAggregateTypeClient interface {
	Recv() (*Record, error)
	grpc.ClientStream
}

type rangeDBEventsByAggregateTypeClient struct {
	grpc.ClientStream
}

func (x *rangeDBEventsByAggregateTypeClient) Recv() (*Record, error) {
	m := new(Record)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *rangeDBClient) SubscribeToEvents(ctx context.Context, in *EventsRequest, opts ...grpc.CallOption) (RangeDB_SubscribeToEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RangeDB_serviceDesc.Streams[3], "/rangedbpb.RangeDB/SubscribeToEvents", opts...)
	if err != nil {
		return nil, err
	}
	x := &rangeDBSubscribeToEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RangeDB_SubscribeToEventsClient interface {
	Recv() (*Record, error)
	grpc.ClientStream
}

type rangeDBSubscribeToEventsClient struct {
	grpc.ClientStream
}

func (x *rangeDBSubscribeToEventsClient) Recv() (*Record, error) {
	m := new(Record)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RangeDBServer is the server API for RangeDB service.
type RangeDBServer interface {
	Events(*EventsRequest, RangeDB_EventsServer) error
	EventsByStream(*EventsByStreamRequest, RangeDB_EventsByStreamServer) error
	EventsByAggregateType(*EventsByAggregateTypeRequest, RangeDB_EventsByAggregateTypeServer) error
	SubscribeToEvents(*EventsRequest, RangeDB_SubscribeToEventsServer) error
}

// UnimplementedRangeDBServer can be embedded to have forward compatible implementations.
type UnimplementedRangeDBServer struct {
}

func (*UnimplementedRangeDBServer) Events(req *EventsRequest, srv RangeDB_EventsServer) error {
	return status.Errorf(codes.Unimplemented, "method Events not implemented")
}
func (*UnimplementedRangeDBServer) EventsByStream(req *EventsByStreamRequest, srv RangeDB_EventsByStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method EventsByStream not implemented")
}
func (*UnimplementedRangeDBServer) EventsByAggregateType(req *EventsByAggregateTypeRequest, srv RangeDB_EventsByAggregateTypeServer) error {
	return status.Errorf(codes.Unimplemented, "method EventsByAggregateType not implemented")
}
func (*UnimplementedRangeDBServer) SubscribeToEvents(req *EventsRequest, srv RangeDB_SubscribeToEventsServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeToEvents not implemented")
}

func RegisterRangeDBServer(s *grpc.Server, srv RangeDBServer) {
	s.RegisterService(&_RangeDB_serviceDesc, srv)
}

func _RangeDB_Events_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RangeDBServer).Events(m, &rangeDBEventsServer{stream})
}

type RangeDB_EventsServer interface {
	Send(*Record) error
	grpc.ServerStream
}

type rangeDBEventsServer struct {
	grpc.ServerStream
}

func (x *rangeDBEventsServer) Send(m *Record) error {
	return x.ServerStream.SendMsg(m)
}

func _RangeDB_EventsByStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EventsByStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RangeDBServer).EventsByStream(m, &rangeDBEventsByStreamServer{stream})
}

type RangeDB_EventsByStreamServer interface {
	Send(*Record) error
	grpc.ServerStream
}

type rangeDBEventsByStreamServer struct {
	grpc.ServerStream
}

func (x *rangeDBEventsByStreamServer) Send(m *Record) error {
	return x.ServerStream.SendMsg(m)
}

func _RangeDB_EventsByAggregateType_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EventsByAggregateTypeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RangeDBServer).EventsByAggregateType(m, &rangeDBEventsByAggregateTypeServer{stream})
}

type RangeDB_EventsByAggregateTypeServer interface {
	Send(*Record) error
	grpc.ServerStream
}

type rangeDBEventsByAggregateTypeServer struct {
	grpc.ServerStream
}

func (x *rangeDBEventsByAggregateTypeServer) Send(m *Record) error {
	return x.ServerStream.SendMsg(m)
}

func _RangeDB_SubscribeToEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RangeDBServer).SubscribeToEvents(m, &rangeDBSubscribeToEventsServer{stream})
}

type RangeDB_SubscribeToEventsServer interface {
	Send(*Record) error
	grpc.ServerStream
}

type rangeDBSubscribeToEventsServer struct {
	grpc.ServerStream
}

func (x *rangeDBSubscribeToEventsServer) Send(m *Record) error {
	return x.ServerStream.SendMsg(m)
}

var _RangeDB_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rangedbpb.RangeDB",
	HandlerType: (*RangeDBServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Events",
			Handler:       _RangeDB_Events_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "EventsByStream",
			Handler:       _RangeDB_EventsByStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "EventsByAggregateType",
			Handler:       _RangeDB_EventsByAggregateType_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeToEvents",
			Handler:       _RangeDB_SubscribeToEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "rangedb.proto",
}
