// Code generated by go generate
// This file was generated at:
// 2020-04-06 15:14:16.362734 -0700 PDT m=+0.001291295
package rangedbtest

import "github.com/inklabs/rangedb"

type eventBinder interface {
	Bind(events ...rangedb.Event)
}

func BindEvents(binder eventBinder) {
	binder.Bind(
		&ThingWasDone{},
		&AnotherWasComplete{},
		&ThatWasDone{},
	)
}
