// Code generated by go generate; DO NOT EDIT.
// This file was generated at
// 2021-01-20 15:37:20.832346 -0800 PST m=+0.001145698
package rangedbtest

import "github.com/inklabs/rangedb"

func BindEvents(binder rangedb.EventBinder) {
	binder.Bind(
		&ThingWasDone{},
		&AnotherWasComplete{},
		&ThatWasDone{},
		&FloatWasDone{},
		&StringWasDone{},
	)
}
