// Code generated by go generate; DO NOT EDIT.
// This file was generated at
// 2020-10-27 16:12:55.702358 -0700 PDT m=+0.001492066
package rangedbtest

import "github.com/inklabs/rangedb"

func BindEvents(binder rangedb.EventBinder) {
	binder.Bind(
		&ThingWasDone{},
		&AnotherWasComplete{},
		&ThatWasDone{},
		&FloatWasDone{},
	)
}
