// Code generated by go generate; DO NOT EDIT.
// This file was generated at
// 2020-10-06 21:19:04.284641 -0700 PDT m=+0.000900120
package chat

import "github.com/inklabs/rangedb"

func BindEvents(binder rangedb.EventBinder) {
	binder.Bind(
		&RoomWasOnBoarded{},
		&RoomWasJoined{},
		&MessageWasSentToRoom{},
		&PrivateMessageWasSentToRoom{},
		&UserWasRemovedFromRoom{},
		&UserWasBannedFromRoom{},
		&UserWasOnBoarded{},
		&UserWasWarned{},
	)
}
