// Code generated by go generate; DO NOT EDIT.
// This file was generated at
// 2020-10-06 21:14:54.927166 -0700 PDT m=+0.001589172
package chat

func (e RoomWasOnBoarded) AggregateID() string   { return e.RoomID }
func (e RoomWasOnBoarded) AggregateType() string { return "room" }
func (e RoomWasOnBoarded) EventType() string     { return "RoomWasOnBoarded" }

func (e RoomWasJoined) AggregateID() string   { return e.RoomID }
func (e RoomWasJoined) AggregateType() string { return "room" }
func (e RoomWasJoined) EventType() string     { return "RoomWasJoined" }

func (e MessageWasSentToRoom) AggregateID() string   { return e.RoomID }
func (e MessageWasSentToRoom) AggregateType() string { return "room" }
func (e MessageWasSentToRoom) EventType() string     { return "MessageWasSentToRoom" }

func (e PrivateMessageWasSentToRoom) AggregateID() string   { return e.RoomID }
func (e PrivateMessageWasSentToRoom) AggregateType() string { return "room" }
func (e PrivateMessageWasSentToRoom) EventType() string     { return "PrivateMessageWasSentToRoom" }

func (e UserWasRemovedFromRoom) AggregateID() string   { return e.RoomID }
func (e UserWasRemovedFromRoom) AggregateType() string { return "room" }
func (e UserWasRemovedFromRoom) EventType() string     { return "UserWasRemovedFromRoom" }

func (e UserWasBannedFromRoom) AggregateID() string   { return e.RoomID }
func (e UserWasBannedFromRoom) AggregateType() string { return "room" }
func (e UserWasBannedFromRoom) EventType() string     { return "UserWasBannedFromRoom" }
