// Code generated by go generate; DO NOT EDIT.
// This file was generated at
// 2020-10-27 16:12:52.822523 -0700 PDT m=+0.000993817
package chat

func (e UserWasOnBoarded) AggregateID() string   { return e.UserID }
func (e UserWasOnBoarded) AggregateType() string { return "user" }
func (e UserWasOnBoarded) EventType() string     { return "UserWasOnBoarded" }

func (e UserWasWarned) AggregateID() string   { return e.UserID }
func (e UserWasWarned) AggregateType() string { return "user" }
func (e UserWasWarned) EventType() string     { return "UserWasWarned" }
