// Code generated by go generate; DO NOT EDIT.
// This file was generated at
// 2021-01-30 11:29:08.177616 -0800 PST m=+0.001769886
package chat

func (c OnBoardUser) AggregateID() string   { return c.UserID }
func (c OnBoardUser) AggregateType() string { return "user" }
func (c OnBoardUser) CommandType() string   { return "OnBoardUser" }

func (c WarnUser) AggregateID() string   { return c.UserID }
func (c WarnUser) AggregateType() string { return "user" }
func (c WarnUser) CommandType() string   { return "WarnUser" }
