// Code generated by go generate; DO NOT EDIT.
// This file was generated at
// 2021-01-15 23:18:17.37513 -0800 PST m=+0.005275011
package chat

func (e UserWasOnBoarded) AggregateID() string   { return e.UserID }
func (e UserWasOnBoarded) AggregateType() string { return "user" }
func (e UserWasOnBoarded) EventType() string     { return "UserWasOnBoarded" }

func (e UserWasWarned) AggregateID() string   { return e.UserID }
func (e UserWasWarned) AggregateType() string { return "user" }
func (e UserWasWarned) EventType() string     { return "UserWasWarned" }
