name: RangeDB build

on:
  pull_request:
    types: [ready_for_review]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.1
        env:
          PG_HOST: 127.0.0.1
          PG_USER: postgres
          PG_DBNAME: github_actions_ci_test
        ports:
        - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.16.2"
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Import Secrets
        uses: hashicorp/vault-action@v2
        with:
          url: http://127.0.0.1:8200
          token: testroot
      - name: Execute install
      - run: | 
          go mod download
          go generate ./...
          go vet ./...
      - name: Execute before_script
      - run: |
          docker run -d -p 8200:8200 -e 'VAULT_DEV_ROOT_TOKEN_ID=testroot' vault
          psql -c 'create database github_actions_ci_test;' -U postgres
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
      - name: Execute scripts
      - run: | 
          go test -v -race -coverprofile c.out.tmp ./...
          cat c.out.tmp | grep -v "_vfsdata.go" | grep -v "_gen.go" | grep -v ".pb.go" | grep -v "/rangedbtest/" | grep -v "/cryptotest/" > c.out
          go tool cover -func c.out
